//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int IdNotes { get; set; }
        public Nullable<double> Note1 { get; set; }
        public Nullable<double> Note2 { get; set; }
        public Nullable<double> Note3 { get; set; }
        public Nullable<double> Note4 { get; set; }
        public Nullable<double> Avarage { get; set; }
        public Nullable<int> IdSubject { get; set; }
    }
}
