//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public string IdStudent { get; set; }
        public string Name { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<int> IdSubject { get; set; }
    }
}
